import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeModeScript } from "flowbite-react";
import "./globals.css";
import ToastsProvider from "@/providers/ToastsProvider";
import Nav from "@/components/Navs/Navbar";
import TokenRefresher from "@/providers/TokenRefresher";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GARAGE-HERO Test",
  description: "Generated by create flowbite react",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className={inter.className}>
        <Nav />
        {children}
        <ToastsProvider />
        <TokenRefresher />
      </body>
    </html>
  );
}
